apiVersion: v1
appVersion: 0.0.3
description: A Helm chart for Jenkins X jx-role-controller
icon: https://avatars2.githubusercontent.com/u/34566050?s=280&v=4
maintainers:
- email: jenkins-x@googlegroups.com
  name: Jenkins X Team
name: jx-role-controller
sources:
- https://github.com/jenkins-x/jx-role-controller
version: 0.0.3
